apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sense-fe-vol
  namespace: sense
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
