apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sense-agent01-vol
  namespace: opennsa
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
